{{- if .Values.profiler.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: profiles-viewer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: profiles-viewer
    odigos.io/system-object: "true"
{{- end }}
