apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: odigos-autoscaler-metrics-server
  name: odigos-autoscaler-metrics-server
  namespace: odigos-system
spec:
  ports:
  - name: https
    port: 4443
    protocol: TCP
    targetPort: 4443
  selector:
    app.kubernetes.io/name: odigos-autoscaler
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: eden-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubernetes-bootcamp
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: number-of-spans
      target:
        type: AverageValue
        averageValue: 100
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: odigos-metrics:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: odigos-autoscaler
  namespace: odigos-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-metrics-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: odigos-autoscaler
  namespace: odigos-system
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    k8s-app: odigos-autoscaler-metrics-server
  name: v1beta1.custom.metrics.k8s.io
spec:
  group: custom.metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: odigos-autoscaler-metrics-server
    namespace: odigos-system
  version: v1beta1
  versionPriority: 100