apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: odiglet
  namespace: odigos-system
subjects:
  - kind: ServiceAccount
    name: odiglet
    namespace: odigos-system
roleRef:
  kind: Role
  name: odiglet
  apiGroup: rbac.authorization.k8s.io
