name: E2E Tests

on:
  pull_request:
    branches:
      - main

jobs:
  kubernetes-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "~1.21.2"
          check-latest: true
      - name: Create Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          cluster_name: kind
      - name: Build CLI
        run: |
          cd cli
          go build -o odigos
      - name: Build and Load Odigos Images
        run: |
          TAG=e2e-test make build-images load-to-kind
      - name: Install Odigos
        run: |
          cli/odigos install --version e2e-test