name: E2E Tests

on:
  pull_request:
    branches:
      - main

jobs:
  kubernetes-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "~1.21.2"
          check-latest: true
      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.9.0
      - name: Create Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          cluster_name: kind
      - name: Build CLI
        run: |
          cd cli
          go build -o odigos
      - name: Build and Load Odigos Images
        run: |
          TAG=e2e-test make build-images load-to-kind
      - name: Install Odigos
        run: |
          cli/odigos install --version e2e-test
      - name: Install Collector - Add Dependencies
        shell: bash
        run: |
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
      - uses: actions/checkout@v4
        with:
          repository: 'open-telemetry/opentelemetry-helm-charts'
          path: opentelemetry-helm-charts
      - name: Install Collector - Helm install
        run: helm install test -f .github/workflows/e2e/collector-helm-values.yaml opentelemetry-helm-charts/charts/opentelemetry-collector --namespace traces --create-namespace
      - name: Wait for Collector to be ready
        run: |
          kubectl wait --for=condition=Ready --timeout=60s -n traces pod/test-opentelemetry-collector-0
      - name: Install KV Shop
        run: |
          kubectl create ns kvshop
          kubectl apply -f .github/workflows/e2e/kv-shop.yaml -n kvshop
      - name: Wait for KV Shop to be ready
        run: |
          kubectl wait --for=condition=Ready --timeout=100s -n kvshop pods --all
      - name: Select kvshop namespace for instrumentation
        run: |
          kubectl label namespace kvshop odigos-instrumentation=enabled
      - name: Connect to Jaeger destination
        run: |
          kubectl create -f .github/workflows/e2e/jaeger-dest.yaml
      - name: Wait for Odigos to bring up collectors
        run: |
          while [[ $(kubectl get daemonset odigos-data-collection -n odigos-system -o jsonpath='{.status.numberReady}') != 1 ]];
          do
          echo "Waiting for odigos-data-collection daemonset to be created" && sleep 3;
          done
          while [[ $(kubectl get deployment odigos-gateway -n odigos-system -o jsonpath='{.status.readyReplicas}') != 1 ]];
          do
          echo "Waiting for odigos-data-collection deployment to be created" && sleep 3;
          done
          kubectl wait --for=condition=Available --timeout=100s deployments --all -n kvshop
          kubectl get pods -A
          kubectl get svc -A
      - name: Start bot job
        run: |
          kubectl create -f .github/workflows/e2e/buybot-job.yaml -n kvshop
      - name: Wait for bot job to complete
        run: |
          kubectl wait --for=condition=Complete --timeout=60s job/buybot-job -n kvshop
      - name: Copy trace output
        run: |
          kubectl cp -c filecp traces/test-opentelemetry-collector-0:tmp/trace.json /tmp/trace.json
          cat /tmp/trace.json